kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: minimal-ingress
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/minimal-ingress
  uid: d0bdf64a-a8e6-4842-83f7-41973c58ec59
  resourceVersion: '21263'
  generation: 2
  creationTimestamp: '2020-12-06T07:24:15Z'
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  managedFields:
    - manager: k8saasapi
      operation: Update
      apiVersion: networking.k8s.io/v1
      time: '2020-12-06T07:24:15Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:nginx.ingress.kubernetes.io/rewrite-target': {}
    - manager: k8saasapi
      operation: Update
      apiVersion: extensions/v1beta1
      time: '2020-12-06T07:24:58Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:rules': {}
    - manager: nginx-ingress-controller
      operation: Update
      apiVersion: networking.k8s.io/v1beta1
      time: '2020-12-06T07:25:13Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:loadBalancer':
            'f:ingress': {}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: backend
              servicePort: 80
status:
  loadBalancer:
    ingress:
      - ip: 159.65.210.224
